### ISSUE TITLE
Load modules and brushes on demand dynamically

### ISSUE THREAD

**Issue by agus-prawoto** [syntaxhighlighter/syntaxhighlighter#395]
Is there any way to load modules and brushes on demand dynamically? as until now, we have to build it all at first.

I've done some test:
- without brushes: 122Kb, 29Kb minified 
- with all brushes: 205Kb, 92Kb minified

I'm in a situation where users have some options to choose what brushes they want to include.
It is possible in version 3 but it seems doesn't possible in version 4, so to accommodate the users need, currently I have to include all the brushes

**Comment by alexgorbatchev** [comment]
Dynamic loading was removed in v4 because bandwidth capacities have increased dramatically since that feature was written. I feel that if you need to provide your users with an option to have all of the brushes available at one point or another, it makes sense to just bundle everything together.

Otherwise you can build custom versions on the server. You could probably reuse current build pipeline to send things straight to the browser and cache.
